services:
  - type: web
    name: youtube-research-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://youtube-research-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true
    plan: free

  - type: web
    name: youtube-research-backend
    env: python
    pythonVersion: 3.11.7
    buildCommand: cd api && pip install -r requirements.txt
    startCommand: cd api && uvicorn api.index:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDioSUyHngF6OIIb-jp7sJ3vSDoSZLDiY4
      - key: PINECONE_API_KEY
        value: pcsk_nXSPy_Ev1R8HosRJj5dbJ1pXCmHipTvcaaaV36dQ53swCbAo6R7RTWVmN8JmQxnjpZWPm
      - key: PINECONE_INDEX
        value: yt-memory
      - key: PINECONE_CLOUD
        value: aws
      - key: PINECONE_REGION
        value: us-east-1
      - key: YOUTUBE_API_KEY
        value: AIzaSyATUUbrkJyOuMp_RimQatbsM0fhviZtWJU
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free 