services:
  - type: web
    name: youtube-research-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://youtube-research-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: youtube-research-backend
    env: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: gunicorn api.index:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true 